# Generated by Django 5.2.5 on 2025-08-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Macroregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Macroregião",
                "verbose_name_plural": "Macroregiões",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "macroregion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regions",
                        to="common.macroregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Região",
                "verbose_name_plural": "Regiões",
            },
        ),
        migrations.CreateModel(
            name="MacroregionAffinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=5, unique=True)),
                ("value", models.IntegerField(verbose_name="Valor de afinidade")),
                (
                    "macroregion1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities_as_source",
                        to="common.macroregion",
                    ),
                ),
                (
                    "macroregion2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities_as_target",
                        to="common.macroregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Afinidade de Macroregiões",
                "verbose_name_plural": "Afinidades de Macroregiões",
                "unique_together": {("macroregion1", "macroregion2")},
            },
        ),
    ]
